import { AppDataState } from './types';

export const MASTER_DIVISIONS: string[] = [
  '01 - Excavation & Earthwork',
  '02 - Concrete & Footings',
  '03 - Foundation Walls',
  '04 - Concrete Slab',
  '05 - Wood Framing & Structure',
  '06 - Roofing & Waterproofing',
  '07 - Thermal Insulation & Vapor Barrier',
  '08 - Drywall & Gypsum Board',
  '09 - Interior & Exterior Finishes',
  '10 - Plumbing Systems',
  '11 - HVAC & Ventilation',
  '12 - Electrical & Low Voltage',
  '13 - Exterior Cladding & Windows',
  '14 - Deck & Porch Construction',
  '15 - Driveway & Concrete Flatwork',
  '16 - Landscaping & Site Finishes',
];

export const INITIAL_DATA: AppDataState = {
  parameters: {
    defaultWasteRate: 0.05, // 5.0%
    contingencyRate: 0.10, // 10.0%
    salesTaxRate: 0.08, // 8.0%
    currencySymbol: '$',
    masterDivisions: [...MASTER_DIVISIONS],
  },
  projectSetup: {
    projectName: 'Riverside Contemporary Residence (Lot 42)',
    projectAddress: '742 Evergreen Terrace, Oakville, ON',
    estimateVersion: 'Rev 1.2 (Pre-Construction Baseline)',
    grossArea: 1850, // 1,850 sq ft
    estimator: 'David Zhang, P.Eng., PQS',
    estimateDate: '2026-08-24',
  },
  subcontractorInfo: {
    subAName: 'Apex Contracting Group',
    subBName: 'BuildTech Solutions Inc.',
    subCName: 'Crestview Builders Ltd.',
  },
  boqItems: [
    // 01 - Excavation
    {
      id: 'EX-001',
      division: '01 - Excavation & Earthwork',
      description: 'Site strip topsoil (6" depth) & stockpile on site',
      drawingRef: 'C-101',
      location: 'Site Footprint',
      baseQty: 3200,
      unit: 'sq ft',
      itemWasteRate: null,
      materialRate: 0.0,
      labourRate: 0.45,
      equipSubRate: 0.85,
    },
    {
      id: 'EX-002',
      division: '01 - Excavation & Earthwork',
      description: 'Basement bulk excavation & ramp formation',
      drawingRef: 'S-101',
      location: 'Basement Level',
      baseQty: 460,
      unit: 'cu yd',
      itemWasteRate: null,
      materialRate: 0.0,
      labourRate: 2.5,
      equipSubRate: 14.2,
    },
    {
      id: 'EX-003',
      division: '01 - Excavation & Earthwork',
      description: 'Granular ' + 'B backfill around foundation & compaction',
      drawingRef: 'S-102',
      location: 'Perimeter Wall',
      baseQty: 185,
      unit: 'ton',
      itemWasteRate: 0.08,
      materialRate: 24.5,
      labourRate: 6.0,
      equipSubRate: 8.5,
    },

    // 02 - Concrete & Footings
    {
      id: 'FT-001',
      division: '02 - Concrete & Footings',
      description: 'Continuous strip footings (24"x10", 25 MPa Concrete)',
      drawingRef: 'S-103',
      location: 'Perimeter Foundation',
      baseQty: 24,
      unit: 'cu yd',
      itemWasteRate: 0.05,
      materialRate: 195.0,
      labourRate: 65.0,
      equipSubRate: 28.0,
    },
    {
      id: 'FT-002',
      division: '02 - Concrete & Footings',
      description: '15M reinforcing rebar for footings & column pads',
      drawingRef: 'S-103',
      location: 'Foundation Footings',
      baseQty: 1420,
      unit: 'lf',
      itemWasteRate: 0.06,
      materialRate: 1.85,
      labourRate: 1.2,
      equipSubRate: 0.0,
    },

    // 03 - Foundation Walls
    {
      id: 'FW-001',
      division: '03 - Foundation Walls',
      description: 'Poured concrete foundation walls (8" thick, 8ft height)',
      drawingRef: 'S-104',
      location: 'Basement Enclosure',
      baseQty: 48,
      unit: 'cu yd',
      itemWasteRate: 0.04,
      materialRate: 215.0,
      labourRate: 95.0,
      equipSubRate: 45.0,
    },
    {
      id: 'FW-002',
      division: '03 - Foundation Walls',
      description: 'Bituminous damp-proofing & dimple drainage membrane',
      drawingRef: 'A-201',
      location: 'Exterior Wall Faces',
      baseQty: 1680,
      unit: 'sq ft',
      itemWasteRate: 0.05,
      materialRate: 1.45,
      labourRate: 0.95,
      equipSubRate: 0.0,
    },

    // 04 - Concrete Slab
    {
      id: 'SL-001',
      division: '04 - Concrete Slab',
      description: 'Basement concrete floor slab (4" thick with 6x6 wire mesh)',
      drawingRef: 'S-105',
      location: 'Basement Floor',
      baseQty: 1050,
      unit: 'sq ft',
      itemWasteRate: 0.05,
      materialRate: 4.8,
      labourRate: 2.75,
      equipSubRate: 1.1,
    },
    {
      id: 'SL-002',
      division: '04 - Concrete Slab',
      description: '4" crushed stone sub-base layer & 10 mil poly vapor retarder',
      drawingRef: 'S-105',
      location: 'Under Slab',
      baseQty: 1050,
      unit: 'sq ft',
      itemWasteRate: 0.08,
      materialRate: 1.35,
      labourRate: 0.65,
      equipSubRate: 0.35,
    },

    // 05 - Wood Framing & Structure
    {
      id: 'FR-001',
      division: '05 - Wood Framing & Structure',
      description: '2x6 exterior load-bearing wall framing @ 16" O.C.',
      drawingRef: 'A-102',
      location: '1st & 2nd Floors',
      baseQty: 2450,
      unit: 'sq ft',
      itemWasteRate: 0.07,
      materialRate: 6.85,
      labourRate: 4.2,
      equipSubRate: 0.0,
    },
    {
      id: 'FR-002',
      division: '05 - Wood Framing & Structure',
      description: 'Engineered I-Joist floor system (11-7/8" with 3/4" T&G subfloor)',
      drawingRef: 'S-201',
      location: 'Main & Upper Floor',
      baseQty: 1850,
      unit: 'sq ft',
      itemWasteRate: 0.05,
      materialRate: 8.4,
      labourRate: 3.6,
      equipSubRate: 0.0,
    },
    {
      id: 'FR-003',
      division: '05 - Wood Framing & Structure',
      description: 'Engineered wood roof truss package & 1/2" OSB sheathing',
      drawingRef: 'S-202',
      location: 'Roof Structure',
      baseQty: 1450,
      unit: 'sq ft',
      itemWasteRate: 0.05,
      materialRate: 9.6,
      labourRate: 4.8,
      equipSubRate: 1.5,
    },

    // 06 - Roofing & Waterproofing
    {
      id: 'RF-001',
      division: '06 - Roofing & Waterproofing',
      description: 'Architectural asphalt shingles (30-year lifetime rating)',
      drawingRef: 'A-301',
      location: 'Pitched Roof Area',
      baseQty: 1650,
      unit: 'sq ft',
      itemWasteRate: 0.1,
      materialRate: 2.65,
      labourRate: 2.1,
      equipSubRate: 0.0,
    },
    {
      id: 'RF-002',
      division: '06 - Roofing & Waterproofing',
      description: 'Synthetic underlayment, ice & water shield, drip edges',
      drawingRef: 'A-301',
      location: 'Eaves & Valleys',
      baseQty: 1650,
      unit: 'sq ft',
      itemWasteRate: 0.05,
      materialRate: 0.95,
      labourRate: 0.65,
      equipSubRate: 0.0,
    },

    // 07 - Thermal Insulation
    {
      id: 'IN-001',
      division: '07 - Thermal Insulation & Vapor Barrier',
      description: 'R-24 batt insulation for 2x6 exterior walls + 6 mil poly',
      drawingRef: 'A-401',
      location: 'Exterior Envelope',
      baseQty: 2450,
      unit: 'sq ft',
      itemWasteRate: 0.05,
      materialRate: 1.75,
      labourRate: 0.85,
      equipSubRate: 0.0,
    },
    {
      id: 'IN-002',
      division: '07 - Thermal Insulation & Vapor Barrier',
      description: 'R-50 blown-in cellulose attic insulation',
      drawingRef: 'A-401',
      location: 'Attic Space',
      baseQty: 1250,
      unit: 'sq ft',
      itemWasteRate: 0.05,
      materialRate: 1.6,
      labourRate: 0.75,
      equipSubRate: 0.25,
    },

    // 08 - Drywall
    {
      id: 'DW-001',
      division: '08 - Drywall & Gypsum Board',
      description: '1/2" drywall on walls & ceilings (taped, 3-coat finish to Level 4)',
      drawingRef: 'A-501',
      location: 'All Living Spaces',
      baseQty: 6800,
      unit: 'sq ft',
      itemWasteRate: 0.08,
      materialRate: 1.25,
      labourRate: 1.85,
      equipSubRate: 0.0,
    },

    // 09 - Finishes
    {
      id: 'FN-001',
      division: '09 - Interior & Exterior Finishes',
      description: 'Engineered hardwood flooring (main floor living & dining)',
      drawingRef: 'A-502',
      location: 'Main Level',
      baseQty: 950,
      unit: 'sq ft',
      itemWasteRate: 0.08,
      materialRate: 7.2,
      labourRate: 3.4,
      equipSubRate: 0.0,
    },
    {
      id: 'FN-002',
      division: '09 - Interior & Exterior Finishes',
      description: 'Porcelain floor & wall tile in master & powder bathrooms',
      drawingRef: 'A-503',
      location: 'Bathrooms',
      baseQty: 380,
      unit: 'sq ft',
      itemWasteRate: 0.1,
      materialRate: 8.5,
      labourRate: 6.8,
      equipSubRate: 0.0,
    },
    {
      id: 'FN-003',
      division: '09 - Interior & Exterior Finishes',
      description: 'Interior trim package (doors, baseboard 5-1/4", casings, hardware)',
      drawingRef: 'A-504',
      location: 'Throughout House',
      baseQty: 1,
      unit: 'lot',
      itemWasteRate: null,
      materialRate: 8400.0,
      labourRate: 4800.0,
      equipSubRate: 0.0,
    },

    // 10 - Plumbing
    {
      id: 'PL-001',
      division: '10 - Plumbing Systems',
      description: 'Complete rough-in piping (PEX water lines & PVC DWV stacks)',
      drawingRef: 'M-101',
      location: 'Basement to 2nd Flr',
      baseQty: 1,
      unit: 'lot',
      itemWasteRate: null,
      materialRate: 4200.0,
      labourRate: 5600.0,
      equipSubRate: 650.0,
    },
    {
      id: 'PL-002',
      division: '10 - Plumbing Systems',
      description: 'Fixture trim package (toilets, sinks, tubs, faucets, tankless water heater)',
      drawingRef: 'M-102',
      location: 'Kitchen & Baths',
      baseQty: 1,
      unit: 'lot',
      itemWasteRate: null,
      materialRate: 6800.0,
      labourRate: 2400.0,
      equipSubRate: 0.0,
    },

    // 11 - HVAC
    {
      id: 'HV-001',
      division: '11 - HVAC & Ventilation',
      description: 'High-efficiency 96% AFUE gas furnace & 2.5-ton AC condenser',
      drawingRef: 'M-201',
      location: 'Mechanical Room',
      baseQty: 1,
      unit: 'lot',
      itemWasteRate: null,
      materialRate: 7200.0,
      labourRate: 2800.0,
      equipSubRate: 350.0,
    },
    {
      id: 'HV-002',
      division: '11 - HVAC & Ventilation',
      description: 'Supply & return sheet metal ductwork + HRV system installation',
      drawingRef: 'M-202',
      location: 'Distribution Run',
      baseQty: 1,
      unit: 'lot',
      itemWasteRate: null,
      materialRate: 3600.0,
      labourRate: 3200.0,
      equipSubRate: 0.0,
    },

    // 12 - Electrical
    {
      id: 'EL-001',
      division: '12 - Electrical & Low Voltage',
      description: '200A main service panel, copper wiring, standard LED recessed pots',
      drawingRef: 'E-101',
      location: 'Whole House',
      baseQty: 1,
      unit: 'lot',
      itemWasteRate: null,
      materialRate: 5900.0,
      labourRate: 6800.0,
      equipSubRate: 450.0,
    },
    {
      id: 'EL-002',
      division: '12 - Electrical & Low Voltage',
      description: 'Low voltage structured cabling (Cat6, TV, security pre-wire)',
      drawingRef: 'E-102',
      location: 'Whole House',
      baseQty: 1,
      unit: 'lot',
      itemWasteRate: null,
      materialRate: 1450.0,
      labourRate: 1200.0,
      equipSubRate: 0.0,
    },

    // 13 - Exterior Cladding & Windows
    {
      id: 'EX-CL01',
      division: '13 - Exterior Cladding & Windows',
      description: 'Triple-pane Low-E vinyl window package & insulated exterior doors',
      drawingRef: 'A-202',
      location: 'Exterior Openings',
      baseQty: 1,
      unit: 'lot',
      itemWasteRate: null,
      materialRate: 16500.0,
      labourRate: 3800.0,
      equipSubRate: 600.0,
    },
    {
      id: 'EX-CL02',
      division: '13 - Exterior Cladding & Windows',
      description: 'Fiber cement lap siding & stone veneer accent on front elevation',
      drawingRef: 'A-203',
      location: 'Exterior Facades',
      baseQty: 2200,
      unit: 'sq ft',
      itemWasteRate: 0.06,
      materialRate: 4.85,
      labourRate: 4.25,
      equipSubRate: 0.0,
    },

    // 14 - Deck & Porch
    {
      id: 'DK-001',
      division: '14 - Deck & Porch Construction',
      description: 'Rear composite deck (14x16 ft) with aluminum baluster railing',
      drawingRef: 'A-105',
      location: 'Rear Yard',
      baseQty: 224,
      unit: 'sq ft',
      itemWasteRate: 0.05,
      materialRate: 24.5,
      labourRate: 14.0,
      equipSubRate: 0.0,
    },

    // 15 - Driveway
    {
      id: 'DR-001',
      division: '15 - Driveway & Concrete Flatwork',
      description: 'Poured concrete double driveway with broom finish & front walkway',
      drawingRef: 'C-102',
      location: 'Front Approach',
      baseQty: 750,
      unit: 'sq ft',
      itemWasteRate: 0.05,
      materialRate: 6.2,
      labourRate: 3.8,
      equipSubRate: 1.2,
    },

    // 16 - Landscaping
    {
      id: 'LS-001',
      division: '16 - Landscaping & Site Finishes',
      description: 'Final grading, premium Kentucky Bluegrass sodding & foundation shrubs',
      drawingRef: 'L-101',
      location: 'Front & Rear Yards',
      baseQty: 1,
      unit: 'lot',
      itemWasteRate: null,
      materialRate: 3400.0,
      labourRate: 2800.0,
      equipSubRate: 650.0,
    },
  ],
  subcontractorQuotes: {
    '01 - Excavation & Earthwork': { subAQuote: 14200, subBQuote: 13800, subCQuote: 15100 },
    '02 - Concrete & Footings': { subAQuote: 11400, subBQuote: 12100, subCQuote: 10900 },
    '03 - Foundation Walls': { subAQuote: 21500, subBQuote: 20800, subCQuote: 22400 },
    '04 - Concrete Slab': { subAQuote: 11800, subBQuote: 11200, subCQuote: 12500 },
    '05 - Wood Framing & Structure': { subAQuote: 62000, subBQuote: 59500, subCQuote: 63800 },
    '06 - Roofing & Waterproofing': { subAQuote: 11200, subBQuote: 10800, subCQuote: 11900 },
    '07 - Thermal Insulation & Vapor Barrier': { subAQuote: 9600, subBQuote: 9200, subCQuote: 9900 },
    '08 - Drywall & Gypsum Board': { subAQuote: 23500, subBQuote: 22800, subCQuote: 24200 },
    '09 - Interior & Exterior Finishes': { subAQuote: 31000, subBQuote: 29500, subCQuote: 32400 },
    '10 - Plumbing Systems': { subAQuote: 21000, subBQuote: 20400, subCQuote: 21800 },
    '11 - HVAC & Ventilation': { subAQuote: 18200, subBQuote: 17800, subCQuote: 19100 },
    '12 - Electrical & Low Voltage': { subAQuote: 16800, subBQuote: 16200, subCQuote: 17500 },
    '13 - Exterior Cladding & Windows': { subAQuote: 44000, subBQuote: 42500, subCQuote: 45800 },
    '14 - Deck & Porch Construction': { subAQuote: 9400, subBQuote: 9100, subCQuote: 9800 },
    '15 - Driveway & Concrete Flatwork': { subAQuote: 9200, subBQuote: 8900, subCQuote: 9600 },
    '16 - Landscaping & Site Finishes': { subAQuote: 7400, subBQuote: 7100, subCQuote: 7800 },
  },
  budgetControls: {
    '01 - Excavation & Earthwork': { approvedBudget: 14500, actualCost: 14100 },
    '02 - Concrete & Footings': { approvedBudget: 11500, actualCost: 11250 },
    '03 - Foundation Walls': { approvedBudget: 21000, actualCost: 22350 }, // Over budget demo
    '04 - Concrete Slab': { approvedBudget: 12000, actualCost: 11600 },
    '05 - Wood Framing & Structure': { approvedBudget: 60000, actualCost: 61400 }, // Over budget demo
    '06 - Roofing & Waterproofing': { approvedBudget: 11500, actualCost: 10950 },
    '07 - Thermal Insulation & Vapor Barrier': { approvedBudget: 9500, actualCost: 9150 },
    '08 - Drywall & Gypsum Board': { approvedBudget: 23000, actualCost: 22700 },
    '09 - Interior & Exterior Finishes': { approvedBudget: 30000, actualCost: 28900 },
    '10 - Plumbing Systems': { approvedBudget: 20500, actualCost: 20100 },
    '11 - HVAC & Ventilation': { approvedBudget: 18000, actualCost: 17650 },
    '12 - Electrical & Low Voltage': { approvedBudget: 16500, actualCost: 16200 },
    '13 - Exterior Cladding & Windows': { approvedBudget: 43000, actualCost: 44200 }, // Over budget demo
    '14 - Deck & Porch Construction': { approvedBudget: 9500, actualCost: 9050 },
    '15 - Driveway & Concrete Flatwork': { approvedBudget: 9000, actualCost: 8850 },
    '16 - Landscaping & Site Finishes': { approvedBudget: 7200, actualCost: 6900 },
  },
  lastSaved: new Date().toISOString(),
};
